aws_region=eu-central-1
bucket_name=openbagetest
url:https://openbagetest.s3.eu-central-1.amazonaws.com
tx_recipient_address=0x9879B435E9c1c5984CdEa39c9393aE3D6289b050
tx_hash=0x2eebb750325990b70732716b60e45461d405bcc58edd9f4b02ec6232b24b038f
badge_file_url=https://openbagetest.s3.eu-central-1.amazonaws.com/assertion-660f78f0-4.json

MAX_CRITERIA_COUNT=100
aws_peer=
scadenza_token=30m
scadenza_refreshToken=1y
CLIENT_SECRET=d3J0BcMNHcAV+Weog62o3S8vV3vUprUh73PTRwUYXvk=
client_id_1=test
client_secret_1=test

imageUrl=https://openbagetest.s3.eu-central-1.amazonaws.com/logo/logoOpenBadge.png